# Generated by Django 2.0.2 on 2018-04-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('P', 'স্থায়ী ঠিকানা'), ('C', 'বর্তমান ঠিকানা')], max_length=50, null=True)),
                ('house_no', models.CharField(blank=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, max_length=200, null=True)),
                ('postoffice', models.CharField(blank=True, max_length=200, null=True)),
                ('up_word_no', models.CharField(blank=True, max_length=200, null=True)),
                ('union', models.CharField(blank=True, max_length=200, null=True)),
                ('upazila', models.CharField(blank=True, max_length=200, null=True)),
                ('zila', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spous_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nid', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('brn', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'পুরুষ'), ('F', 'মহিলা')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_type', models.CharField(blank=True, choices=[('personal', 'personal'), ('office', 'office'), ('home', 'home')], max_length=50, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_phone', to='contacts.Person')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_email', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_address', to='contacts.Person'),
        ),
    ]
