# Generated by Django 2.0.2 on 2018-04-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOfLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='class_name')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Khatiyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khatiyan_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='khatiyan_no')),
                ('signed_date', models.DateField()),
                ('remark', models.TextField(blank=True, max_length=500, null=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khat_investigated_by', to='contacts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='KhatiyanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandOwnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_land', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('class_of_land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.ClassOfLand')),
                ('khatiyan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.Khatiyan')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Mouza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouza_name', models.CharField(max_length=100, verbose_name='mouza_name')),
                ('jl_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='jl_no')),
                ('upazila', models.CharField(blank=True, max_length=100, null=True, verbose_name='upazila')),
            ],
            options={
                'verbose_name': 'Mouza',
                'verbose_name_plural': 'Mouzas',
            },
        ),
        migrations.CreateModel(
            name='MouzaMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_of_land', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('total_khas_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_bondobosto_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_recorded_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_orpito_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_jolashoy', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_cultivation', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_hill', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_forest', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_unused', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('mouja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.Mouza')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='plot_no')),
                ('mouza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.Mouza')),
            ],
            options={
                'verbose_name': 'Plot',
                'verbose_name_plural': 'Plots',
            },
        ),
        migrations.CreateModel(
            name='PlotMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_of_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_khas_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_bondobosto_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_recorded_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_orpito_land', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_jolashoy', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_cultivation', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_hill', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_forest', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('total_unused', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.Plot')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='landownerinfo',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.Plot'),
        ),
        migrations.AddField(
            model_name='landownerinfo',
            name='type_of_land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.TypeOfLand'),
        ),
        migrations.AddField(
            model_name='khatiyan',
            name='khatiyan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.KhatiyanType'),
        ),
        migrations.AddField(
            model_name='khatiyan',
            name='mouza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landinfo.Mouza'),
        ),
        migrations.AddField(
            model_name='khatiyan',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khat_prepared_by', to='contacts.Person'),
        ),
    ]
