# Generated by Django 2.0.2 on 2018-04-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouzameta',
            old_name='total_bondobosto_land',
            new_name='alluvion_diluvion',
        ),
        migrations.RenameField(
            model_name='mouzameta',
            old_name='total_khas_land',
            new_name='non_settleable_land',
        ),
        migrations.RenameField(
            model_name='mouzameta',
            old_name='total_orpito_land',
            new_name='settleable_land',
        ),
        migrations.RenameField(
            model_name='mouzameta',
            old_name='total_recorded_land',
            new_name='surrendered_land',
        ),
    ]
