# Generated by Django 2.0.2 on 2018-04-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoujaMeta',
            new_name='MouzaMeta',
        ),
    ]
