# Generated by Django 2.0.2 on 2018-04-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landinfo', '0003_auto_20180425_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('mouza', 'plot_no')},
        ),
    ]
