# Generated by Django 2.0.2 on 2018-04-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landinfo', '0004_auto_20180424_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouza',
            name='total_amount_of_land',
        ),
        migrations.AddField(
            model_name='mouzameta',
            name='total_amount_of_land',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
